version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx_conf:/etc/nginx
      - ${PWD}/src/lamp/app/static:/var/www/static
    networks:
      - frontend
    restart: always

  lamp:
    image: krizex/lamp:latest
    container_name: lamp
    volumes:
      - /var/lamp/log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
    env_file: database.conf
    networks:
      - frontend
      - backend
    restart: always

  pg:
    image: postgres:10-alpine
    container_name: pg
    volumes:
      - /var/lamp/db:/var/lib/postgresql/data:rw
    env_file: database.conf
    networks:
      - backend
    restart: always

  lamp-lbt:
    image: krizex/lbt:latest
    container_name: lamp-lbt
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    restart: always


networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge
